image: maven:3-jdk-11

junit-test:
  stage: test
  script:
    - mvn -f pom.xml test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

