image: maven:3-jdk-11

stages:
  - build

maven-build:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/reports/TEST-*.xml
    reports:
      junit:
        - target/reports/TEST-*.xml
