image: maven:3-jdk-11

stages:
  - build
  - test
  - deploy

#compile:
#  stage: build
#  script:
#    - mvn -f pom.xml clean validate
#    - mvn -f pom.xml clean compile 
    
#junit-test:
# stage: test
#  script:
#    - mvn -f pom.xml clean test
#  artifacts:
#    paths:
#      - target/surefire-reports/TEST-*.xml
#    reports:
#      junit:
#        - target/surefire-reports/TEST-*.xml

create-jar:
  stage: deploy
  script:
    - mvn -f pom.xml clean package
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git add -f target/CCN.jar
    - git commit -m "Add jar"
    - git remote rm origin && git remote add origin git@collaborating.tuhh.de:e16/courses/software-development/ss22/group04_coop/collaborative-carrier-network.git
    - git push origin HEAD:master
